import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// create font for css variable
const poppins = Poppins({
   subsets: ["latin"],
   weight: ["400", "500", "600", "700"],
   variable: "--font-poppins",
});

export const metadata: Metadata = {
   title: "Event App",
   description: "Generated by create next app",
   icons: {
      icon: "/favicon.svg",
   },
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={poppins.variable}>{children}</body>
      </html>
   );
}
